[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build -w backend"

[deploy]
startCommand = "npm run start -w backend"
healthcheckPath = "/api/v1/health"
restartPolicyType = "on_failure"
